### ISSUE TITLE
Traceback from exceptions accumulates on REPL on 4.1.0

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_MIDI#28]
Observed on `4.1.0-rc.1` and briefly discussed on Discord. `4.1.0` has same issue with accumulation of stack trace stuff in `Traceback` output:

```
Adafruit CircuitPython 4.1.0 on 2019-08-03; Adafruit Metro M4 Express with samd51j19
>>> from adafruit_midi.program_change import ProgramChange
>>> ProgramChange(200) ### intentional illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
ValueError: Out of range
>>> ProgramChange(200) ### intentional illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
ValueError: Out of range
>>> ProgramChange(200) ### intentional illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
  File "<stdin>", line 1, in <module>
  File "adafruit_midi/program_change.py", line 56, in __init__
ValueError: Out of range
```

**Comment by kevinjwalters** [comment]
I just caught all exceptions including `KeyboardInterrupt` on 6.3.0 and that also accumulates in a similar fashion when reading from a powered off PMS5003 with `adafruit_pm25`.

**Comment by tannewt** [comment]
Please try absolute latest and file a new issue if the problem persists.
